# Generated by Django 4.2 on 2023-05-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
