# Generated by Django 4.2 on 2023-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_checklist_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='is_delete',
            field=models.BooleanField(),
        ),
    ]
