# Generated by Django 4.2 on 2023-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_alter_checklist_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='is_delete',
            field=models.BooleanField(default=True),
        ),
    ]
