# Generated by Django 4.2 on 2023-05-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0005_alter_checklist_created_on_alter_checklist_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='title',
            field=models.CharField(max_length=5),
        ),
    ]
